version: "2"
services:
  app:
   build: 
     context: ./app
   links:
     - db
   ports:
     - "5000:5000"
   depends_on:
     - db
   volumes:
     - ./app:/app
      
  db:
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: